### ISSUE TITLE
Find technology for creating neural network

### ISSUE THREAD

**Issue by ferc255** [ssu-451/project#3]
Hello guys!

First we need to do is to find some framework or library for creating neural networks.

Describe it in #4

**Comment by CatAlexandra** [comment]
@ferc255 we need to find algorithm, not a library.

**Comment by ferc255** [comment]
Try to find video tutorials on youtube.com. This method is usually very useful for me.

**Comment by ferc255** [comment]
[Нейронные сети за 30 минут: от теории до практики.](https://www.youtube.com/watch?v=AZG0j0pNY-4)

**Comment by zerosigma** [comment]
I search for text recognition algorithms in English.

**Comment by ferc255** [comment]
That's a very good idea because you can hardly find any good literature in Russian (generally).

**Comment by zerosigma** [comment]
[https://pdfs.semanticscholar.org/a8d5/90ebecbf7d8307969bdf1b786570ad66b51a.pdf](url)

**Comment by ferc255** [comment]
We decided that we'll do everything manually, almost without specific libraries. As for neural network, the algorithm is back propagation.
