### ISSUE TITLE
Извлечение символов из изображения

### ISSUE THREAD

**Issue by volkovda351** [ssu-451/project#6]
Написать алгоритм, который разбивает входное изображение на несколько изображений символов

**Comment by volkovda351** [comment]
Полезный материал http://mechanoid.kiev.ua/cv-text-image-segmentator.html

**Comment by KolesnikovaTamara** [comment]
I'll do it

**Comment by esikachev** [comment]
@KolesnikovaTamara please, update us

**Comment by KolesnikovaTamara** [comment]
Closed in #30
